CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE public.mock_data (
    id serial PRIMARY KEY,
    customer_first_name character varying(50),
    customer_last_name character varying(50),
    customer_age integer,
    customer_email character varying(50),
    customer_country character varying(50),
    customer_postal_code character varying(50),
    customer_pet_type character varying(50),
    customer_pet_name character varying(50),
    customer_pet_breed character varying(50),
    seller_first_name character varying(50),
    seller_last_name character varying(50),
    seller_email character varying(50),
    seller_country character varying(50),
    seller_postal_code character varying(50),
    product_name character varying(50),
    product_category character varying(50),
    product_price real,
    product_quantity integer,
    sale_date date,
    sale_customer_id integer,
    sale_seller_id integer,
    sale_product_id integer,
    sale_quantity integer,
    sale_total_price real,
    store_name character varying(50),
    store_location character varying(50),
    store_city character varying(50),
    store_state character varying(50),
    store_country character varying(50),
    store_phone character varying(50),
    store_email character varying(50),
    pet_category character varying(50),
    product_weight real,
    product_color character varying(50),
    product_size character varying(50),
    product_brand character varying(50),
    product_material character varying(50),
    product_description character varying(1024),
    product_rating real,
    product_reviews integer,
    product_release_date date,
    product_expiry_date date,
    supplier_name character varying(50),
    supplier_contact character varying(50),
    supplier_email character varying(50),
    supplier_phone character varying(50),
    supplier_address character varying(50),
    supplier_city character varying(50),
    supplier_country character varying(50)
);